# cloudbuild.worker.yaml
# Builds the worker Docker image and deploys it to Cloud Run.
# This version uses the project's Default Compute Service Account.

timeout: "1200s"

substitutions:
  _REGION: europe-west1
  _AR_REPO: stella
  _SERVICE: stella-worker
  _IMAGE_TAG: latest

steps:
  # ------------------------------------------------------------------------------------
  # STEP 1 & 2: Build and Push the Docker image. (No changes)
  # ------------------------------------------------------------------------------------
  - name: gcr.io/cloud-builders/docker
    id: Build
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:${_IMAGE_TAG}
      - -f
      - Dockerfile.worker
      - .
  - name: gcr.io/cloud-builders/docker
    id: Push
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:${_IMAGE_TAG}

  # ------------------------------------------------------------------------------------
  # STEP 3: Deploy the new image to Cloud Run.
  # This step is simplified to use the default service account.
  # ------------------------------------------------------------------------------------
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Deploy
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:${_IMAGE_TAG}
      - --region=${_REGION}
      - --no-allow-unauthenticated
      # --- REMOVED: Redis secret is no longer needed. ---
      - --set-secrets=OLLAMA_BASE_URL=OLLAMA_BASE_URL:latest,NASA_API_KEY=NASA_API_KEY:latest,GOOGLE_CUSTOM_SEARCH_KEY=GOOGLE_CUSTOM_SEARCH_KEY:latest,GOOGLE_CUSTOM_SEARCH_CX=GOOGLE_CUSTOM_SEARCH_CX:latest
      # --- REMOVED: Redis and BullMQ env vars are no longer needed. ---
      - --update-env-vars=NODE_ENV=production
      # --- REMOVED: The --service-account flag has been removed. ---
      # By removing this flag, Cloud Run will automatically assign the project's
      # Default Compute Service Account as the identity for this service.
      - --concurrency=4
      - --cpu=1
      - --memory=512Mi
      - --max-instances=3

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:${_IMAGE_TAG}