# cloudbuild.worker.yaml
# Build & deploy the stella-worker container to Cloud Run (Service).

timeout: "1200s"

substitutions:
  _REGION: europe-west1
  _AR_REPO: stella
  _SERVICE: stella-worker
  _IMAGE_TAG: latest
  # Optional: pin a runtime service account (leave blank to keep existing)
  _RUNTIME_SA: ""

steps:
  # ---------------------------------------------------------------------------
  # Build
  # ---------------------------------------------------------------------------
  - name: gcr.io/cloud-builders/docker
    id: Build
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:${_IMAGE_TAG}
      - -f
      - Dockerfile.worker
      - .

  # ---------------------------------------------------------------------------
  # Push
  # ---------------------------------------------------------------------------
  - name: gcr.io/cloud-builders/docker
    id: Push
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:${_IMAGE_TAG}

  # ---------------------------------------------------------------------------
  # Deploy
  # ---------------------------------------------------------------------------
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Deploy
    entrypoint: bash
    args:
      - -ceu
      - |
        set -euo pipefail

        BASE_ARGS=(
          run deploy ${_SERVICE}
          --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:${_IMAGE_TAG}
          --region=${_REGION}
          --no-allow-unauthenticated
          --set-secrets=CLOUD_RUN_WORKER_URL=CLOUD_RUN_WORKER_URL:latest,OLLAMA_BASE_URL=OLLAMA_BASE_URL:latest,NASA_API_KEY=NASA_API_KEY:latest,GOOGLE_CUSTOM_SEARCH_KEY=GOOGLE_CUSTOM_SEARCH_KEY:latest,GOOGLE_CUSTOM_SEARCH_CX=GOOGLE_CUSTOM_SEARCH_CX:latest,INTERACTIVE_TASKS_QUEUE_ID=INTERACTIVE_TASKS_QUEUE_ID:latest,BACKGROUND_TASKS_QUEUE_ID=BACKGROUND_TASKS_QUEUE_ID:latest
          --update-env-vars=NODE_ENV=production
          --concurrency=4
          --cpu=1
          --memory=512Mi
          --max-instances=3
          --timeout=600
          --cpu-boost
          --execution-environment=gen2
        )

        if [ -n "${_RUNTIME_SA}" ]; then
          gcloud "${BASE_ARGS[@]}" --service-account="${_RUNTIME_SA}"
        else
          gcloud "${BASE_ARGS[@]}"
        fi

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:${_IMAGE_TAG}
